sudo: required
language: node_js
node_js:
  - "4.2"

before_install:
 - sudo apt-get update
 - sudo apt-get install curl php5-cli git
 - curl -sS https://getcomposer.org/installer | php -- --install-dir=bin --filename=composer

install:
  - npm start
