sudo: required
language: php
php: 
 - '5.6'

before_install:
 - sudo apt-get update
 - sudo apt-get install nodejs
 - sudo apt-get install npm

install:
  - npm install

notifications:
  slack:
   rooms:
    - o111:wOdZh9RyHDVyaQhhx9UUf8QU